import pyautogui
from time import sleep

pyautogui.hotkey('win', 'e')                    
sleep(2)
pyautogui.press('tab')
pyautogui.press('tab')      
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('tab')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
pyautogui.press('down')
